name: Deploy React Web to Server

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Use Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Clear
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            rm -rf /home/koselikh/cv.aayurtshrestha.com.np/*

      - name: Deploy to server test 1
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SERVER_PORT }}
          strip_components: 2
          source: build/*
          target: /home/koselikh/cv.aayurtshrestha.com.np

     
       
